<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - Back</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="css/normalize.css"/>
    <link rel="stylesheet" href="css/style.css">
</head>
<body class="grid">
    <header>
        <?php require('partials/header.php') ?> 
    </header>

    <main class="backPage">
        <?php if (array_key_exists('info', $_SESSION) && !empty($_SESSION['info'])): ?>
            <p class="validate"><?= $_SESSION['info']?></p>
        <?php endif; ?>

        <?php if (array_key_exists('user', $_SESSION) && !empty($_SESSION['user'])): ?>
            <?php if ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
                <p class="validate">Salut <?= $_SESSION['user']['firstName'] ?> !</p>
            <?php endif; ?>  
            
            <a href='logout.php' class="logout">Déconnexion</a>
            <div class="dashboard">
                <div class="dashboardAction">
                    <p>Consulter, modifier, supprimer une réservation, un contact...</p> 
                    <button type="button" id="showBookings" class="dashboardButton">acceder</button>
                </div>
                <div class="dashboardAction">
                    <p>Consulter, modifier la liste des préstations <em>(tarif, nombre de participants)</em></p>
                    <button type="button" onclick="window.location.href = 'backActivities.php';" class="dashboardButton">acceder</button>
                </div>
            </div>
        <?php else: ?>
            <form action = "backBookings.php" method="post">
                <label for="mail">Email</label>
                <input type="text" id="mail" name="mail" placeholder="email@example.com" required>
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="password">
                <button type="submit" class="connect">Se connecter</button>
            </form>
        <?php endif; ?>

        <?php if (array_key_exists('error', $_SESSION) && !empty($_SESSION['error'])): ?>
            <p class='alert'><?= $_SESSION['error'][0] ?></p>
        <?php endif; ?>

        <div id="backBooking-content">
        </div>
            
        <div class="modale hide">
            <div id="modale-message">
            </div>
            <i class="modaleButton fas fa-times" onclick="hideModale()"></i>
        </div>
    </main>
    <footer>
        <?php require("partials/footer.php") ?>
    </footer>
    <script src="js/jquery-3.4.1.min.js"></script>
    <script>
        // jQuery - display alert 4sec
        $(".alert, .validate").delay(4000).fadeOut()
    </script>
    <script src="js/backBookings.js"></script>
</body>
</html>