<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - contact Page</title>
    <link rel="icon" href="resources/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="" type="css/normalize/css" />
    <link rel="stylesheet" href="css/style.css">
</head>
<body id="contact">
    <header class="container">
        <?php require('partials/header.php') ?>
    </header>
    <main class="contact">
        <h1>Formulaire de <span>contact</span></h1>
        <p>Pour toute demande de renseignement(s), merci de remplir le formulaire ci-dessous<small>(<span>*</span> Mentions obligatoires)</small></p>

        <?php if (isset($_SESSION) && !empty($_SESSION['error'])): ?>
            <div class="alert">
                <?php foreach ($_SESSION['error'] as $value): ?>
                    <p><?= $value ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if (isset($_SESSION) && empty($_SESSION['error']) && !empty($_SESSION['info'])): ?>
            <div class="alert">
                <p><?= $_SESSION['info'] ?></p>
            </div>
        <?php endif; ?>

        <form id="contactForm" action="contact.php" method="post">
            <label for="email">E-mail<span>*</span></label><input class="field" type="email" id="email" name="email" require autofocus>
            <label for="lastName">Nom<span>*</span></label><input class="field" type="text" id="lastName" name="nom" require>
            <label for="firstName">Prénom<span>*</span></label><input class="field" type="text" id="firstName" name="prenom" require>
            <label for="phone">Téléphone</label><input class="field" type="phone" id="phone" name="telephone">
            <label for="message">Message<span>*</span></label><textarea class="field" id="message" name="message" rows="10" require></textarea>
            <button type="submit">Envoyer</button>
        </form>
        <p>Vous pouvez également nous contacter par téléphone au <a href="tel:0658355166">06.58.35.51.66.</a></p>
    </main>
    <footer>
        <?php require('partials/footer.php') ?>
    </footer>

    <script type="module" src="js/app.js"></script>
</body>
