<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="ROC Multisport, une expérience unique entre lac et montagne !">
    <title>ROC Multisport - Home Page</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" type="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <?php require('partials/header.php') ?> 
    </header>

    <main>
        <?php if (isset($_SESSION) && empty($_SESSION['error']) && !empty($_SESSION['info'])): ?>
            <div class="validate">
                <p><?= $_SESSION['info'] ?></p>
            </div>
        <?php endif; ?>
        <section  id="home" class="home">
            <div class="background">
                <h1>UN ENCADREMENT <span>MULTISPORT</span><br>ENTRE LAC ET MONTAGNE</h1>
                <p>Envie de s'évader, de profiter de la nature autour d'Annecy et de s'initier aux disciplines sportives entre lac et montagne? ROC MULTISPORT est là pour vous!</p>
                <p>Venez découvrir nos activités outdoors, été comme hiver, avec des moniteurs passionnés et qualifiés. Composez vous même votre "cocktail d'activités ROC" à la journée ou sur un week-end complet.</p>
                <p><span>Vivez votre propre excursion!</span></p>
                <p>ROC MULTISPORT vous assure une ambiance unique et une expérience inoubliable !!! Du lac d'Annecy aux sommets des Aravis, venez tester l'aventure : sensations et souvenirs garantis!</p>
                <ul>
                    <li>
                        <div class="img">
                            <img src="img/home_vtt.jpeg" alt="Photo de cycliste sur un vttae">
                        </div>    
                        <div class="vttaeBloc text">
                            <h2>vttae</h2>
                            <a href="#bike">en savoir +</a>
                            <img src="img/picto/vttPicto.png" alt="pictogramme vtt">
                        </div>
                    </li>
                    <li>
                        <div class="img">
                            <img src="img/home_paddle.jpeg" alt="Photo d'un homme en sortie paddle">
                        </div>    
                        <div class="paddleBloc text">
                            <h2>paddle kayak</h2>
                            <a href="#paddle">en savoir +</a>
                            <img src="img/picto/paddlePicto.png" alt="pictogramme paddle">
                        </div>
                    </li>
                    <li>
                        <div class="img">
                            <img src="img/home_climbing.jpeg" alt="Photo d'une femme sur une falaise">
                        </div>    
                        <div class="climbingBloc text">
                            <h2>escalade via ferrata</h2>
                            <a href="#climbing">en savoir +</a>
                            <img src="img/picto/climbingPicto.png" alt="pictogramme climbing">
                        </div>
                    </li>
                    <li>
                        <div class="img">
                            <img src="img/home_archery.jpeg" alt="Photo d'un archer devant une cible">
                        </div>    
                        <div class="archeryBloc text">
                            <h2>tir à l'arc</h2>
                            <a href="#archery">en savoir +</a>
                            <img src="img/picto/archeryPicto.png" alt="pictogramme tir à l'arc">
                        </div>
                    </li>
                    <li>
                        <div class="img">
                            <img src="img/home_snowboard.jpeg" alt="Photo d'un snowboarder">
                        </div>    
                        <div class="snowboardBloc text">
                            <h2>snowboard splitboard</h2>
                            <a href="#snowboard">en savoir +</a>
                            <img src="img/picto/snowboardPicto.png" alt="pictogramme snowboard">
                        </div>
                    </li>
                    <li>
                        <div class="cocktailBottom img">
                            <img src="img/background/bgCocktailHome.jpg" alt="">
                            <p>COMPOSEZ LIBREMENT VOTE <span>COCKTAIL D'ACTIVITÉS!</span></p>
                        </div>
                        <div class="cocktail text">
                            <h2>c<span>o</span><span>c</span><span>k</span>t<span>a</span><span>i</span><span>l</span> roc</h2>
                            <a href="#cocktail"> <span>e</span><span>n</span> <span>s</span><span>a</span><span>v</span><span>o</span><span>i</span><span>r</span> <span>+</span> </a>
                        </div>
                    </li>
                </ul>
            </div>
        </section>
        <section id="bike">
            <div class="bike activity">
                <h2>vttae</h2>
                <h3>vtt <span>à</span> A<span>ssistance</span> É<span>lectrique</span></h3>
                <div class='left_bloc'>
                    <div class="slider">
                        <div><img src="img/vtt_1.jpeg" alt="Photo de 2 cyclistes"></div>
                        <div><img src="img/vtt_2.png" alt="Photo d'un vttae"></div>
                        <div><img src="img/vtt_4.jpeg" alt="Photo d'un cycliste en forêt"></div>
                        <div><img src="img/vtt_5.png" alt="Photo d'une cycliste au sommet d'une montagne"></div>
                    </div>
                    <div class="button desktop-button">
                        <a href="booking.php">réserver</a>
                        <a href="contact.php">contactez-nous</a>
                    </div>
                </div>
                <div class="description">
                    <article>
                        <p>Partez à la découverte de lieux insolites par l'intermédiaire du VTTAE. Depuis la Clusaz, venez vous échapper vers le lac des Confins, le col des Aravis ou encore le plateau de Beauregard. Le bassin Annecien offre lui aussi de multiples randonnées à réaliser en famille ou entre amis.</p>
                        <p>Du plateau des glières à la descente du Semnoz, le VTT à assistance électrique vous permettra d'atteindre de magnifiques points de vue. Avec un profond respect de la nature, en fonction de vos attentes et de vos capacités physiques, votre moniteur mettra tout en oeuvre pour vous offrir la sortie la plus adaptée. Un moment mémorable à venir partager avec ROC MULTISPORT.</p>
                    </article>
                    <article class="price">
                        <h3>tarifs vttae</h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS SANS LOCATION VTT</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">45€/personne</td>
                                </tr>
                                <tr>
                                    <td>1 journée</td>
                                    <td class="tablePrice">80€/personne</td>
                                </tr>
                            </table>
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS AVEC LOCATION VTT</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">80€/personne</td>
                                </tr>
                                <tr>
                                    <td>1 journée</td>
                                    <td class="tablePrice">130€/personne</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 8 personnes maximum, activité disponible à partir de 4 participants. Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>
                        </div>
                        <div class="info">
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 1er Avril au 31 Octobre.</p>
                            <p>À partir de 8 ans. Encadrement et matériel fourni: VTTAE, casque, gants... Une bonne condition physique et des vêtements adaptés sont indispensables à la pratique du VTTAE. Les activités sportives de montagne sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                </div>
                <div class="button mobile-button">
                    <a href="booking.php">réserver</a>
                    <a href="contact.php">contactez-nous</a>
                </div>
            </div>
        </section>
        <section id="paddle">
            <div class="paddle activity">
                <h2>paddle / kayak</h2>
                <div class="left_bloc">
                    <div class="slider">
                        <div><img src="img/kayak_1.jpeg" alt="Photo d'une jeune femme en kayak"></div>
                        <div><img src="img/paddle_1.jpeg" alt="Photo d'un garçon sur un paddle"></div>
                        <div><img src="img/kayak_3.jpeg" alt="Photo d'un homme en kayak"></div>
                    </div>
                    <div class="button desktop-button">
                        <a href="booking.php">réserver</a>
                        <a href="contact.php">contactez-nous</a>
                    </div>
                </div>
                <div class="description">
                    <article>
                        <h3 class="firstActivity">paddle</h3>
                        <p>À la surface de l'eau, venez tester les bienfaits du paddle. Cette discipline accessible à tous, melant équilibre et tonicité, vous permettra d'apprécier les eaux bleues du lac d'Annecy. </p>
                        <p>Parfaitement détendu, déplacez-vous le long des rives jusqu'aux réserves naturelles qui bordent le lac. Vous contemplerez tout au long de votre excursion la faune et la flore ainsi que les magnifiques points de vue qu'offre ce lieu magique. Au ras de l'eau et entouré de somptueuses montagnes, ROC MULTISPORT vous propose de découvrir le paddle dans une atmosphère calme et agréable: une sortie nautique à ne pas manquer!</p>
                    </article>
                    <article class="price">
                        <h3>tarifs paddle</h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">55€/personne</td>
                                </tr>
                                <tr>
                                    <td>1 journée</td>
                                    <td class="tablePrice">100€/personne</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 8 personnes maximum, activité disponible à partir de 4 participants. Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>
                        </div>
                        <div class="info">
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 1er Mai au 31 Octobre.</p>
                            <p>À partir de 6 ans. Encadrement et matériel fourni: Paddle, pagaie, gilet... Une bonne condition physique ainsi que des vêtements adaptés sont indispensables à la pratique du paddle. Les activités sportives de montagne sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                    <article>
                        <h3>kayak</h3>
                        <p>Envie d'une escapade agréable en Kayak ? ROC MULTISPORT vous conseille de tenter l'expérience de la ballade le long des berges du lac d'Annecy.</p>
                        <p>Avec ses multiples paysages, nous vous proposons de découvrir des sites insolites au fil de l'eau. Entre amis ou en famille, cette sortie vous amènera près du Roc de Chèvre où vous pourrez tester quelques sauts rafraîchisssants! Votre moniteur vous apportera toutes les techniques nécessaires au bon déroulement de l'activité et vous délivrera ses connaissances de la faune et de la flore environnante. Un moment appaisant avec ROC MULTISPORT qui plaira aux petits et grands !</p>
                    </article>
                    <article class="price">
                        <h3>tarif kayak</h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIF</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">50€/personne</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 8 personnes maximum, activité disponible à partir de 4 participants. Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>    
                        </div>
                        <div class="info">
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 1er Mai au 31 Octobre.</p>
                            <p>À partir de 6 ans. Encadrement et matériel fourni: Kayak, pagaie, gilet... Une bonne condition physique ainsi que des vêtements adaptés sont indispensables à la pratique du paddle. Les activités sportives de montagne sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                </div>
                <div class="button mobile-button">
                    <a href="booking.php">réserver</a>
                    <a href="contact.php">contactez-nous</a>
                </div>
            </div>
        </section>
        <section id="climbing">
            <div class="climbing activity">
                <h2>escalade / via-ferrata</h2>
                <div class="left_bloc">
                    <div class="slider">
                        <div><img src="img/climbing_1.jpeg" alt="Photo d'un homme le long d'une falaise"></div>
                        <div><img src="img/via_1.jpeg" alt="Photo d'un homme sur une via-ferrata"></div>
                        <div><img src="img/climbing_2.jpeg" alt="Photo d'un groupe en sortie via-ferrata"></div>
                        <div><img src="img/via_2.png" alt="Photo d'une jeune femme sur un pont de singe"></div>
                    </div>
                    <div class="button desktop-button">
                        <a href="booking.php">réserver</a>
                        <a href="contact.php">contactez-nous</a>
                    </div>
                </div>
                <div class="description">
                    <article>
                        <h3 class="firstActivity">escalade</h3>
                        <p>L'escalade vous offrira la possibilité, au contact du rocher, de vous dépasser, de tester votre confiance en vous et surtout d'observer un paysage époustouflant !</p>
                        <p>Du débutant à l'initié, il existe de nombreux lieux de pratique autour d'Annecy. Prendre de la hauteur sur les falaises école du mont Veyrier, vaincre le jeu d'équilibre de la dalle du Roc des Boeufs ou affronter la verticalité des parois du Parmelan; venez découvrir avec ROC MULTISPORT une activité grisante dans un environnement calme et majestueux !</p>
                    </article>
                    <article class="price">
                        <h3>tarifs escalade </h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">50€/personne</td>
                                </tr>
                                <tr>
                                    <td>1 journée</td>
                                    <td class="tablePrice">90€/personne</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 8 personnes maximum, activité disponible à partir de 4 participants. Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>
                        </div>
                        <div class="info">
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 1er Mai au 31 Octobre.</p>
                            <p>À partir de 8 ans. Encadrement et matériel fourni: baudriers, casques, descendeurs, cordes, mousquetons... Une bonne condition physique ainsi que des vêtements adaptés sont indispensables à la pratique de l'escalade. Les activités sportives de montagne sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                    <article>
                        <h3>via ferrata</h3>
                        <p>Entre escalade et randonnée verticale, la via-ferrata vous permettra de savourer, en toute sécurité grâce à une ligne de vie métallique, les délices de la hauteur. De la tour Jallouvre au col des Aravis en passant par la Roche à l'Agathe, découvrez une activité excitante et accessible à tous.</p>
                        <p>Encadré d'un moniteur qualifié, traversez pont de singe, poutre suspendue, tyroliennes, gravissez des échelons métalliques... autant d'éléments vertigineux qui vous feront vivre une expérience unique au milieu de paysages à couper le souffle. Prenez de la hauteur avec ROC MULTISPORT afin de vous confronter à vos limites et apprécier la liberté des grands espaces !</p>
                    </article>
                    <article class="price">
                        <h3>tarifs via ferrata </h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">60€/personne</td>
                                </tr>
                                <tr>
                                    <td>1 journée (2 via-ferrata)</td>
                                    <td class="tablePrice">110€/personne</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 8 personnes maximum, activité disponible à partir de 4 participants. Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>
                        </div>
                        <div class="info">
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 1er Mai au 31 Octobre.</p>
                            <p>À partir de 8 ans. Encadrement et matériel fourni: baudriers, casques, descendeurs, cordes, mousquetons... Une bonne condition physique ainsi que des vêtements adaptés sont indispensables à la pratique de la via-ferrata. Les activités sportives de montagne sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                </div>
                <div class="button mobile-button">
                    <a href="booking.php">réserver</a>
                    <a href="contact.php">contactez-nous</a>
                </div>
            </div>
        </section>
        <section id="archery">
            <div class="archery activity">
                <h2>tir à l'arc</h2>
                <div class="left_bloc">
                    <div class="slider">
                        <div><img src="img/archery_1.jpeg" alt="Photo d'un homme qui tir à l'arc"></div>
                        <div><img src="img/archery_2.jpeg" alt="Photo d'une cible"></div>
                        <div><img src="img/archery_3.jpeg" alt="Photo d'un enfant qui tire à l'arc"></div>
                    </div>
                    <div class="button desktop-button">
                        <a href="booking.php">réserver</a>
                        <a href="contact.php">contactez-nous</a>
                    </div>
                </div>
                <div class="description">
                    <article>
                        <p>Avec Roc MULTISPORT, venez vous initier au tir à l'arc. Cette discipline qui allie précision et concentration vous permettra de passer un moment ludique. A proximité de superbes montagnes et du lac d'Annecy, tester votre adresse en toute sécurité au travers d'une activité plaisante qui développera votre rigueur et votre coordination. Avec une panoplie de jeux pédagogiques, votre moniteur vous apprendra les techniques de base du tir à l'arc.</p>
                        <p>Dans une ambiance convivale, ROC MULTISPORT vous convie à essayer un sport divertissant et accessible à tous. Une expérience à partager en famille ou entre amis!</p>
                    </article>
                    <article class="price">
                        <h3>tarif tir à l'arc</h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIF</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">50€/personne</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 12 personnes maximum, activité disponible à partir de 6 participants, sauf si vous avez opté pour un "Cocktail d'activités.</td>
                                </tr>
                            </table>
                        </div>
                        <div class="info">
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 1er Mai au 31 Octobre.</p>
                            <p>À partir de 7 ans. Encadrement et matériel fourni: arc, flèches, cibles, blasons... Activité réalisée dans un lieu adapté. Une bonne coordination ainsi que des vêtements adaptés sont indispensables à la pratique du tir à l'arc. Les activités sportives de montagne  sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                </div>
                <div class="button mobile-button">
                    <a href="booking.php">réserver</a>
                    <a href="contact.php">contactez-nous</a>
                </div>
            </div>
        </section>
        <section id="snowboard" >
            <div class="snowboard activity">
                <h2>snowboard / splitboard</h2>
                <div class="left_bloc">
                    <div class="slider">
                        <div><img src="img/splitboard_1.jpeg" alt="Photo d'un groupe en sortie splitboard"></div>
                        <div><img src="img/splitboard_2.jpeg" alt="Photo d'une splitboard devant un paysage de montagnes"></div>
                        <div><img src="img/snowboard_1.jpeg" alt="Photo d'un snowboarder"></div>
                    </div>
                    <div class="button desktop-button">
                        <a href="booking.php">réserver</a>
                        <a href="contact.php">contactez-nous</a>
                    </div>
                </div>
                <div class="description">
                    <article>
                        <p>Au départ de La Clusaz, venez vous initier au snowboard avec ROC MULTISPORT: du stage débutant à la journée randonnée splitboard, sans oublier les initiations freestyle ! N'hésitez pas à découvrir cette discipline hivernale sur les pentes enneigées de la station.</p>
                        <p>Accompagné d'un monteur spécialisé snowboard, vous pourrez arpenter les grands espaces des Aravis, découvrir le hors piste et les notions de sécurité ou tout simplement perfectionner vos acquis sur piste. Entouré des splendides montagnes du domaine, venez vibrer sur ce support incroyable: une expérience inoubliable et des sensations garanties !</p>
                    </article>
                    <article class="price">
                        <h3>tarifs snowboard / splitboard</h3>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS SNOWBOARD</th>
                                </tr>
                                <tr>
                                    <td>Stage Rookeasy (débutant) 3x 1/2 journée</td>
                                    <td class="tablePrice">180€/pers.</td>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">160€/pers.</td>
                                </tr>
                                <tr>
                                    <td>1 journée</td>
                                    <td class="tablePrice">330€/pers.</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 8 personnes maximum, activité disponible à partir de 2 participants (3 pour le Rookeasy). Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>
                            <table>
                                <tr>
                                    <th colspan="2">TARIFS RANDO SPLITBOARD</th>
                                </tr>
                                <tr>
                                    <td>1/2 journée</td>
                                    <td class="tablePrice">180€/pers.</td>
                                </tr>
                                <tr>
                                    <td>1 journée</td>
                                    <td class="tablePrice">330€/pers.</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Groupe de 6 personnes maximum, activité disponible à partir de 2 participants. Possibilité de compléter un groupe déjà inscrit.</td>
                                </tr>
                            </table>
                        </div>
                        <div>
                            <p>Infos pratiques</p>
                            <p>Activité disponible du 15 Décembre au 30 Avril.</p>
                            <p>À partir de 7 ans. Encadrement compris, matériel non fourni. Une bonne condition physique et des vêtements adaptés sont indispensables à la pratique du snowboard. Les activités sportives de montagne  sont soumises aux aléas de la météo.</p>
                            <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                            <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                        </div>
                    </article>
                </div>
                <div class="button mobile-button">
                    <a href="booking.php">réserver</a>
                    <a href="contact.php">contactez-nous</a>
                </div>
            </div>
        </section>
        <section id="cocktail">
            <div class="cocktail activity">
                <h2>
                c<span>o</span><span>c</span><span>k</span>t<span>a</span><span>i</span><span>l</span> d'activités <span>r</span><span>o</span><span>c</span>
                </h2>
                <div class="left_bloc">
                    <div class="slider">
                        <div><img src="img/paddle_sunset.jpeg" alt="Photo d'un homme en paddle au couché du soleil"></div>
                        <div><img src="img/vtt_6.jpeg" alt="Photo d'un groupe en sortie vttae"></div>
                        <div><img src="img/archery_4.jpeg" alt="Photo d'un groupe en activité tir à l'arc"></div>
                    </div>
                    <div class="button desktop-button">
                        <a href="booking.php">réserver</a>
                        <a href="contact.php">contactez-nous</a>
                    </div>
                </div>
                <div class="description">
                    <article>
                        <p>Infos pratiques</p>
                        <p>Formule disponible du 1er Mai au 31 Octobre.</p>
                        <p>À partir de 7 ans. Encadrement et matériel compris (sauf snowboard, splitboard, matériel de sécurité: dva, pelle, sonde). Transport compris jusqu'à 5 personnes (2ème véhicule nécessaire au-delà). Pour le matériel hivernal, pensez à vous renseigner sur la location de votre équipement avant toute réservation.</p>
                        <p>Une bonne condition physique est fortement recommandée pour les deux formules. Des vêtements et des chaussures adaptées sont indispensables à la pratique des disciplines outdoor. Les activités sportives de montagne sont soumises aux aléas de la météo.</p>
                        <p>Pensez à vérifier que vous êtes assurés en cas d'annulation ou de maladie.</p>
                        <p>Pour toute demande particulière, <a href="contact.php">contactez-nous</a>! (groupes de plus de 8 personnes, séminaires, collectivités, EVG/EVF, anniversaires...)</p>
                    </article>
                    <article class="price"> 
                        <h3>tarifs c<span>o</span><span>c</span><span>k</span>t<span>a</span><span>i</span><span>l</span></h3>
                        <div class="info">
                            <p><strong>COMPOSEZ LIBREMENT VOTRE COCKTAIL D'ACTIVITÉS</strong></p>
                            <p>Groupe de 8 personnes maximum, activité disponible à partir de 4 participants. Possibilité de compléter un groupe déjà inscrit.</p>
                        </div>
                        <div class="table">
                            <table>
                                <tr>
                                    <th colspan="2"><span>TARIFS COCKTAIL</span></th>
                                </tr>
                                <tr>
                                    <td><span>ROC Day</span><br>2 activités différentes au choix<br></td>
                                    <td class="tablePrice">à partir de 85€/personne</td>
                                </tr>
                                <tr>
                                    <td><span>ROC Week-end</span><br>jusqu'à 4 activités différentes au choix</td>
                                    <td class="tablePrice">à partir de 170€/personne</td>
                                </tr>
                            </table>
                        </div>    
                    </article>
                </div>
                <div class="button mobile-button">
                    <a href="booking.php">réserver</a>
                    <a href="contact.php">contactez-nous</a>
                </div>
            </div>
        </section>
        <section id="testimony">
            <div class="testimony">
            <h2>témoignages</h2>
                <div class="sliderBloc">
                    <div class="slider">
                        <div>
                            <p>"Je n'ai qu'un mot ! Wahou !!! Des paysages de dingue, une magnifique journée en pleine de la nature avec en prime des sensations fortes !"</p>
                            <p>Delphine, ESCALADE</p>
                        </div>
                        <div>
                            <p>"Une vraie découverte pour moi. Un moniteur hyper sympa et des vélos qui avancent tout seuls... J'adore."</p>
                            <p>Jérome, VTTAE</p>
                        </div>
                        <div>
                            <p>"Journée exceptionnelle avec des paysages époustouflants. Un kiff à l'état pur ! Je recommande vivement !"</p>
                            <p>Hervé, randonnée splitboard</p>
                        </div>
                    </div>
                    <!-- <div class="button">
                        <a href="testimony.phtml" title="Consultez les témoignages de tous nos clients en cliquant içi !">tous les témoignages </a>
                    </div> -->
                </div>
            </div>
        </section>
    </main>

    <footer id="footer">
        <?php require('partials/footer.php') ?>
    </footer>

    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="slick/slick.min.js"></script>
    <script type="module" src="js/app.js"></script>
    <script>
        $(document).ready(function(){
            $('.slider').slick({
            // setting-name: setting-value
                autoplay: true,
                autoplaySpeed: 3000,
                arrows: true,
            });
        });
    </script>

    
</body>
</html>