<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - Politique de confidentialité</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="" type="css/normalize/css" />
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <?php require('partials/header.php') ?> 
    </header>   
    <main class="policy">
        <h1>MENTIONS LEGALES ET CONDITIONS GENERALES D’UTILISATION</h1>
        <p>Dernière mise à jour effectuée le : 28 Mai 2021</p>
        <p><span>Préambule</span></p>
        <p>La poursuite de la navigation sur notre Site www.rocmultisport.fr vaut de la part des utilisateurs une acceptation sans réserve des dispositions et conditions d’utilisation qui suivent (ci-après dénommées « <span>C.G.U.</span> »). Avant toute utilisation des fonctionnalités de notre site, l’utilisateur reconnaît avoir pris connaissance des présentes C.G.U. et les avoir acceptés.</p>
        <p>La version actuellement en ligne de nos C.G.U. est la seule opposable pendant toute la durée d’utilisation du site et jusqu’à ce que nous la remplacions par une nouvelle version.</p>
        <p>Notre Société – <em>ROC MULTISPORT</em> – se réserve le droit de modifier les présentes conditions à tout moment, il est donc de la responsabilité des utilisateurs de consulter les C.G.U. régulièrement. Toute utilisation de notre site après modification des C.G.U. vaut acceptation irrévocable par l’utilisateur de la nouvelle version. En cas de désaccord avec nos C.G.U. l’utilisateur est invité à ne plus utiliser notre Site.</p>

        <h2>ARTICLE 1 – DEFINITIONS </h2>
        <p>Sur notre site internet, les termes ci-dessous ont la signification suivante :</p>
        <ul>
            <li>
                <p><span>« Contenu »</span> : désigne l’ensemble des éléments constituant l’information présente sur notre Site (textes, images, vidéos, algorithmes, logiciels, widgets, etc.) et permettant son fonctionnement, l’information de l’Utilisateur et la présentation de nos services ;</p>
            </li>
            <li>
                <p><span>« Droits de propriété intellectuelle »</span> : désigne tous les droits de propriété intellectuelle et droits connexes (droit d’auteur, droits de marque, droits de brevets, noms commerciaux, bases de données, etc.) tels que protégés par le Code de la Propriété Intellectuelle créé par la loi n°92-587 du 1er juillet 1992, dont la version en vigueur est celle applicable au moment de la consultation du site par l’utilisateur ; </p>
            </li>
            <li>
                <p><span>« Fonctionnalités »</span> : désigne tous les droits de propriété intellectuelle et droits connexes (droit d’auteur, droits de marque, droits de brevets, noms commerciaux, bases de données, etc.) tels que protégés par le Code de la Propriété Intellectuelle créé par la loi n°92-587 du 1er juillet 1992, dont la version en vigueur est celle applicable au moment de la consultation du site par l’utilisateur ;</p>
            </li>
            <li>
                <p><span>« Fonctionnalités »</span> : désigne toutes les fonctionnalités mises à disposition de nos utilisateurs via notre site ;</p>
            </li>
            <li>
                <p><span>« Site »</span> : désigne le site internets www.rocmultisport.fr ou tout autre site internet exploité par la Société et mis à disposition de l’Utilisateur ;</p>
            </li>
            <li>
                <p><span>« Société »</span> : désigne ROC MULTISPORT, Société à Actions Simplifiées, au capital social de 5.000 €, immatriculée au R.C.S. de Annecy sous le n°879 169 514 et dont le siège social est sis 165 Route des Tappes 74230 Dingy-Saint-Clair ;</p>
            </li>
            <li>
                <p><span>« Utilisateur »</span> : désigne tout individu utilisant notre Site et ayant accès à son contenu ;</p>
            </li>
        </ul>

        <h2>ARTICLE 2 – MENTIONS LEGALES</h2>
        <p>En application de <em>la loi n°2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique</em>, il est indiqué aux utilisateurs de notre site, l’identité des intervenants dans le cadre de sa réalisation et de son suivi :</p>
        <p>Propriétaire : ROC MULTISPORT, Société à Actions Simplifiées, au capital social de 5.000 €, immatriculée au R.C.S. de Annecy sous le n°879 169 514 et dont le siège social est sis 165 Route des Tappes 74230 Dingy-Saint-Clair ;</p>
        <p>Développeur :  Benoît Flipot / benoit@rocmultisport.fr</p>
        <p>Hébergeur : HOSTINGER INTERNATIONAL Ltd., 61 Lordou Vironos Str. 6023 Larnaca, Chypre</p>
        <p>Délégué à la Protection des Données : remi@rocmultisport.fr / benoit@rocmultisport.fr</p>
        <p>Directeur de la publication du Site : Rémi Spéra</p>
        
        <h2>ARTICLE 3 – PROTECTION DES DONNEES A CARACTERE PERSONNEL</h2>
        <p>Pour l’utilisation de notre Site, nous allons procéder au traitement de certaines données à caractère personnel concernant les Utilisateurs. Ces traitements s’effectuent dans le respect de <em>la loi n°78-17 du 6 janvier 1978</em> modifiée relative à l’informatique, aux fichiers et aux libertés (dite « Loi Informatique et Libertés ») et de la Politique de Protection des données accessible dans l’onglet correspondant sur notre site.</p>

        <h2>ARTICLE 4 – ACCES AU SITE</h2>
        <p>L’accès au Site et son utilisation sont réservés à un usage strictement personnel. L’Utilisateur s’engage à ne pas utiliser ce Site et les informations ou données qui y figurent à des fins commerciales, politiques, publicitaires et pour toute forme de sollicitation commerciale et notamment l’envoi de courriers électroniques non sollicités.</p>
        <p>La Société ne pourra être tenue pour responsable en cas d’accès au Site par des mineurs pas plus qu’elle ne pourra être tenue pour responsable en cas d’informations erronées ou mensongères fournies par les utilisateurs du Site.</p>

        <h2>ARTICLE 5 – DESCRIPTION DES SERVICES FOURNIS</h2>
        <p>Le Site a pour objet de présenter les services et produits de la Société Roc Multisport aux utilisateurs. Nous nous efforçons de fournir des informations aussi précises que possible, mais nous ne sommes pas responsables des oublis, inexactitudes ou carences dans la mise à jour des informations.</p>
        <p>Toutes les informations fournies sur notre site sont données à titre indicatif et ne sont pas exhaustives, elles sont pourvues sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
        <p>L’Utilisateur est également informé que les photographies présentes sur le Site ne sont pas contractuelles et n’engagent pas la Société Roc Multisport.</p>

        <h2>ARTICLE 6 – PROPRIETE INTELLECTUELLE</h2>
        <ol>
            <li>
                <p>Notre site</p>
                <p>Toutes les marques, photographies, textes, commentaires, illustrations, images animées ou non, séquences vidéo, sons, ainsi que toutes les applications informatiques qui pourraient être utilisées pour faire fonctionner ce site et plus généralement tous les éléments reproduits ou utilisés sur le Site sont protégés par les lois en vigueur au titre de la propriété intellectuelle.</p>
                <p>Ils sont la propriété pleine et entière de la Société Roc Multisport ou de ses partenaires commerciaux. Toute reproduction, représentation, utilisation ou adaptation, sous quelques formes que ce soit, de tout ou partie de ces éléments, y compris les applications informatiques, sans l'accord préalable et écrit de l'éditeur, sont strictement interdites. Le fait pour l'éditeur de ne pas engager de procédure dès la prise de connaissance de ces utilisations non autorisées ne vaut pas acceptation desdites utilisations et renonciation aux poursuites.</p>
                <p>Il est strictement interdit à l’utilisateur de : </p>
                <ul>
                    <li><em>Copier, reproduire, représenter, diffuser, distribuer, publier, de façon permanente ou provisoire, tout ou partie du contenu et/ou du Site par tout moyen et sur tout support connu ou inconnu à ce jour ;</em></li>
                    <li><em>Créer des œuvres dérivées à partir du contenu et/ou du Site ;</em></li>
                    <li><em>Modifier, traduire, adapter, arranger, tout ou partie du Contenu et/ou du Site ;</em></li>
                    <li><em>Désassembler, décompiler, effectuer de l’ingénierie inverse sur le Site.</em></li>
                </ul>
            </li>
            <li>
                <p>Notre marque</p>
                <p>Les marques verbales et visuelles (logos) de la Société sont protégées. La marque Roc Multisport est une marque déposée et protégée auprès de l’INPI. Leur utilisation sans autorisation écrite de notre Société, sur tout support, à des fins de valorisation de produits ou de services, ou à des fins commerciales, est interdite sous peine de poursuites pénales et civiles engagées par notre Société à l’encontre de l’utilisateur et/ou de tiers responsable.</p>
            </li>
        </ol>

        <h2>ARTICLE 7 – GESTION DU SITE</h2>
        <p>Notre Site est normalement accessible à tout moment aux utilisateurs. Pour la bonne gestion du Site, l’éditeur pourra à tout moment se réserver le droit de :</p>
        <ul>
            <li><em>Suspendre, interrompre ou limiter l’accès à tout ou partie du site, pour quelque raison que ce soit, avec ou sans préavis et à sa seule discrétion ;</em></li>
            <li><em>Supprimer toute information pouvant en perturber le fonctionnement, pour quelque raison que ce soit avec ou sans préavis et à sa seule discrétion ;</em></li>
            <li><em>Suspendre le Site afin de procéder à des mises à jour.</em></li>
        </ul>
        <p>Roc Multisport s’efforcera au mieux de communiquer préalablement aux utilisateurs les dates et heures de l’intervention, mais sa responsabilité ne pourrait être recherchée en cas de non-communication préalable.</p>

        <h2>ARTICLE 8 – RESPONSABILITES</h2>
        <ol>
            <li>
                <p>Accès au site</p>
                <p>Notre Société s’engage à faire tout son possible afin que le site soit accessible 24h/24 et 7j/7. Toutefois, notre Société ne prend aucun engagement quant à la disponibilité et l’accessibilité permanente du site et ne garantit pas que le Site soit exempt d’erreurs. La responsabilité de l’éditeur ne peut être engagée en cas de défaillance, panne, difficulté ou interruption de fonctionnement, empêchant l’accès au site ou à une de ses fonctionnalités.</p>
                <p>Notre Société et l’hébergeur ne pourront être tenus responsables en cas de dysfonctionnement du réseau internet, des lignes téléphoniques ou du matériel informatique et de téléphonie lié notamment à l’encombrement du réseau empêchant l’accès au serveur.</p>
                <p>L’éditeur ne pourra être tenu pour responsables en cas de poursuites judiciaires à l’encontre des utilisateurs :</p>
                <ul>
                    <li><em>Du fait de l’usage du site ou de tout autre service accessible via internet ;</em></li>
                    <li><em>Du fait du non-respect par l’utilisateur des présentes CGU.</em></li>
                </ul>
            </li>
            <li>
                <p>Matériel utilisé</p>
                <p>Le matériel de connexion au site utilisé par l’Utilisateur est sous son entière responsabilité. Il doit prendre toutes les mesures appropriées pour protéger son matériel et ses propres données. L’Utilisateur s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur récemment mis-à-jour.</p>
                <p>Roc Multisport n’est pas responsable des dommages causés aux Utilisateurs, à des tiers et/ou à leur équipement du fait de leur connexion ou de leur utilisation du site et les Utilisateurs renoncent à toute action de ce fait contre l’éditeur.</p>
                <p>L’éditeur ne pourra également être tenu pour responsables des dommages indirects (tels par exemple qu’une perte de marché ou perte de chance) consécutifs à l’utilisation du Site.</p>

                <h2>ARTICLE 9 – LIENS HYPERTEXTES</h2>
                <p>La mise en place par les utilisateurs de tout lien hypertexte vers tout ou partie du site est autorisée, sous réserve d’autorisation préalable et écrite de la Société Roc Multisport, sollicitée par courriel aux adresses suivantes : remi@rocmultisport.fr / benoit@rocmultisport.fr</p>
                <p>Roc Multisport est libre de refuser cette autorisation sans avoir à justifier de quelque manière que ce soit sa décision. Dans le cas où la Société accorderait son autorisation, celle-ci n’est dans tous les cas que temporaire et pourra être retirée à tout moment, sans obligation de justification. Dans tous les cas, tout lien devra être retiré sur simple demande de la marque.</p>
                <p>Le Site contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de l’éditeur. Cependant, notre Société n’a pas la possibilité de vérifier le contenu des sites ainsi visités et n’assumera en conséquence aucune responsabilité de ce fait.</p>
            </li>
        </ol>

        <h2>ARTICLE 10 – LOI APPLICABLE</h2>
        <p>Les présentes conditions d’utilisation du site sont régies par la loi française et sont – en cas de litige - soumises à la compétence exclusive de juridiction aux tribunaux compétents de droit commun, sous réserve d’une attribution de compétence spécifique découlant d’un texte de loi ou réglementaire particulier.</p>
    </main>
    <footer>
        <?php require("partials/footer.php") ?>
    </footer>
</body>