<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - Reservation Page</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="css/normalize.css"/>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <?php require('partials/header.php') ?> 
    </header>

    <main class="print">
        <h1>Récapitulatif de votre réservation du <?= $booking_item['dateOfBooking'] ?></h1>
        <div class="recap">
            <?php if ($booking_item['typeOfBooking'] === "singleActivity"): ?>
                <div class="singleActivity">
                    <p>Type de réservation: <em>activité(s) simple(s)</em></p>
                    <?php if (!empty($booking_item['comment'])): ?>
                        <p>Commentaire: 
                            <em><?= $booking_item['comment']?></em>
                        </p>
                    <?php endif; ?>
                    <p>Contact: 
                        <em><?= $contact_item['firstName']?> <?= $contact_item['lastName']?></em>
                    </p>
                    <?php if (!empty($contact_item['organisation'])): ?>
                        <p>Société: 
                            <em><?= $contact_item['organisation']?></em>
                        </p>
                    <?php endif; ?>
                    <?php foreach ($activities_array["records"] as $activity): ?>
                        <div class="activityDetails">
                            <p>Activité: 
                                <em><?= $activity['nameActivity'] ?></em>
                            </p>
                            <?php if ($activity['halfDaySelect'] !== "Journée"): ?>
                                <p>Date d'activité: 
                                    <em><?= $activity['dateActivity'] ?> <?= $activity['halfDaySelect']?></em>
                                </p>
                            <?php else: ?>
                                <p>Date d'activité: 
                                    <em><?= $activity['dateActivity'] ?></em>
                                </p>
                            <?php endif; ?>
                        
                            <?php if ($users_array["numberOfParticipants"] === 1): ?>   
                                <p>Participant: 
                                    <em><?= $activities_array['records'][0]['users'][0]['firstName'] .' '. $activities_array['records'][0]['users'][0]['lastName']?></em>
                                </p>
                            <?php else: ?>
                                <p>Participants: </p> 
                                <ul>
                                    
                                        <?php foreach ($activity['users'] as $user): ?>

                                        <li><em><?= $user['firstName'] .' '. $user['lastName']?></em></li>

                                        <?php endforeach; ?>
                                    
                                </ul>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="basket">
                    <table>
                        <thead>
                            <tr>
                                <th colspan="4">mon panier</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($activities_array['records'] as $activity): ?>
                                <tr>
                                    <td><?= $activity['nameActivity']?></td>
                                    <td><?= $users_array["numberOfParticipants"]. x?></td>
                                    <td><?= $activity['price'].€?></td>
                                    <td><?= $activity['totalActivityPrice'].€?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3">total réservation :</td>
                                <td class="totalPrice"><?= $activities_array["totalPrice"].€ ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            <?php else: ?>
                <div class="rocActivities">
                    <p>Type de réservation:
                        <?php if ($booking_item['typeOfBooking'] === "cocktailOneDay"): ?>
                            <em>Cocktail Roc Day</em>
                        <?php else: ?>
                            <em>Cocktail Roc Week-end</em>
                        <?php endif; ?>
                    </p>
                    <?php if (!empty($booking_item['comment'])): ?>
                        <p>Commentaire: 
                            <em><?= $booking_item['comment']?></em>
                        </p>
                    <?php endif; ?>
                    <p>Contact: 
                        <em><?= $contact_item['firstName']?> <?= $contact_item['lastName']?></em>
                    </p>
                    <?php if (!empty($contact_item['organisation'])): ?>
                        <p>Société: 
                            <em><?= $contact_item['organisation']?></em>
                        </p>
                    <?php endif; ?>
                    <div class="activityDetails">
                        <p>Activités:
                            <ul> 
                                <?php foreach ($activities_array['records'] as $activity): ?>
                                    <li><em><?= $activity['nameActivity'] ?></em></li>
                                <?php endforeach; ?>
                            </ul>
                        </p>
                        <?php if ($booking_item['typeOfBooking'] === "cocktailOneDay"): ?>
                            <p>Date d'activités: 
                                <em><?= $activities_array['records'][0]['dateActivity'] ?></em>
                            </p>
                        <?php else: ?>
                            <p>Dates d'activités: 
                                <em>Week-end du <?= $activities_array['records'][0]['dateActivity'] ?></em>
                            </p>
                        <?php endif; ?>
                        <p>Participants: </p> 
                        <ul>
                            <?php foreach ($activities_array['records'][0]['users'] as $user): ?>

                                <li><em><?= $user['firstName'] .' '. $user['lastName']?></em></li>

                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <div class="basket">
                    <table>
                        <thead>
                            <tr>
                                <th colspan="4">mon panier</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($activities_array['records'] as $activity): ?>
                                <tr>
                                    <td><?= $activity['nameActivity']?></td>
                                    <td><?= $users_array['numberOfParticipants']. x?></td>
                                    <td><?= $activity['price'].€?></td>
                                    <td><?= $activity['totalActivityPrice'].€?></td>
                                </tr>
                            <?php endforeach; ?>
                            <tr>
                                <td colspan="3"><?= $activities[$booking_item['typeOfBooking']]['name'] ?></td>
                                <td><?= "-".$activities_array['totalPrice']*$activities[$booking_item['typeOfBooking']]['price']/100 .€ ?></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3">total réservation :</td>
                                <td class="totalPrice"><?= $activities_array['totalPrice']-$activities_array['totalPrice']*$activities[$booking_item['typeOfBooking']]['price']/100 .€ ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            <?php endif; ?>
        </div>

        <button type="button" id="printButton">Imprimer ma réservation</button>

        
    </main>
    <footer>
        <?php require("partials/footer.php") ?>
    </footer>
    <script src="js/print.js"></script>
</body>
</html>




