<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - Politique de confidentialité</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="css/normalize.css"/>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <?php require('partials/header.php') ?> 
    </header>   
    <main class="policy">
        <h1>POLITIQUE DE PROTECTION DES DONNEES PERSONNELLES</h1>
        <p>Dernière mise à jour effectuée le : 28 Mai 2021</p>
        <p><span>Préambule</span></p>
        <p>Notre politique de protection des données a été établie en accord avec les préconisations de la Commission Nationale de l’informatique et des libertés. Elle a pour objectif d’informer les utilisateurs du Site www.rocmultisport.fr de la façon dont leurs données personnelles sont traitées et des engagements et mesures que nous avons pris afin de veiller au respect des données à caractère personnel des visiteurs, utilisateurs et clients de la Société Roc Multisport. </p>
        <p>Elle a été établie conformément aux dispositions de la<em>Loi Informatique et Liberté du 6 janvier 1978</em>, du <em>Règlement Européen sur les Données Personnelles (R.G.P.D.) du 23 mai 2018 et la Loi de transposition du Règlement Européen sur la Protection des Données Personnelles (R.G.P.D.) du 20 juin 2018</em>.</p>
        <p>La version actuellement publiée sur notre site internet est la version en vigueur de cette politique. La Société se réserve le droit de la modifier à tout instant afin de se conformer aux obligations légales en vigueur. Il est donc de la responsabilité de chaque utilisateur de consulter régulièrement cette politique afin de se tenir informé des derniers changements qui pourraient y être apportés. </p>
        <p>En navigant sur notre site, l’utilisateur reconnaît avoir lu, compris et accepter la présente politique de protection des données. </p>

        <h2>ARTICLE 1 – DEFINITIONS </h2>
        <ol>
            <li>
                <h3>Termes techniques relatif à la protection des données personnelles</h3>
                <p>Sur notre site, les termes ci-dessous ont la signification qui leur est attribuée au sens du R.G.P.D. <em>(art.4)</em> :</p>
                <ul>
                    <li>
                        <p><span>Consentement</span> :<em> « de la personne concernée, toute manifestation de volonté, libre, spécifique, éclairée et univoque par laquelle la personne concernée accepte, par une déclaration ou par un acte positif clair, que des données à caractère personnel la concernant fassent l'objet d'un traitement; »</em></p>
                    </li>
                    <li>
                        <p><span>Données à caractère personnel</span> :<em>« toute information se rapportant à une personne physique identifiée ou identifiable (ci-après dénommée «personne concernée») ; est réputée être une «personne physique identifiable» une personne physique qui peut être identifiée, directement ou indirectement, notamment par référence à un identifiant, tel qu'un nom, un numéro d'identification, des données de localisation, un identifiant en ligne, ou à un ou plusieurs éléments spécifiques propres à son identité physique, physiologique, génétique, psychique, économique, culturelle ou sociale; »</em></p>
                    </li>
                    <li>
                        <p><span>Responsable du traitement</span> :<em>« la personne physique ou morale, l'autorité publique, le service ou un autre organisme qui, seul ou conjointement avec d'autres, détermine les finalités et les moyens du traitement; lorsque les finalités et les moyens de ce traitement sont déterminés par le droit de l'Union ou le droit d'un État membre, le responsable du traitement peut être désigné ou les critères spécifiques applicables à sa désignation peuvent être prévus par le droit de l'Union ou par le droit d'un État membre; »</em></p>
                    </li>
                    <li>
                        <p><span>Sous-traitant</span> :<em>« la personne physique ou morale, l'autorité publique, le service ou un autre organisme qui traite des données à caractère personnel pour le compte du responsable du traitement; »</em></p>
                    </li>
                    <li>
                        <p><span>Traitement</span> :<em>« toute opération ou tout ensemble d'opérations effectuées ou non à l'aide de procédés automatisés et appliquées à des données ou des ensembles de données à caractère personnel, telles que la collecte, l'enregistrement, l'organisation, la structuration, la conservation, l'adaptation ou la modification, l'extraction, la consultation, l'utilisation, la communication par transmission, la diffusion ou toute autre forme de mise à disposition, le rapprochement ou l'interconnexion, la limitation, l'effacement ou la destruction; »</em></p>
                    </li>
                    <li>
                        <p><span>Violation de données à caractère personnel</span> :<em>« une violation de la sécurité entraînant, de manière accidentelle ou illicite, la destruction, la perte, l'altération, la divulgation non autorisée de données à caractère personnel transmises, conservées ou traitées d'une autre manière, ou l'accès non autorisé à de telles données; »</em>.</p>
                    </li>
                </ul>
            </li>
            <li>
                <h3>Autres termes utilisés aux présentes</h3>
                <ul>
                    <li>
                        <p><span>« Politique »</span> : désigne la présente Politique de Protection des Données Personnelles ;</p>
                    </li>
                    <li>
                        <p><span>« Société »</span> : désigne ROC MULTISPORT, Société à Actions Simplifiées, au capital social de 5.000 €, immatriculée au R.C.S. de Annecy sous le n°879 169 514 et dont le siège social est sis 165 Route des Tappes 74230 Dingy-Saint-Clair ;</p>
                    </li>
                    <li>
                        <p><span>« Site »</span>: désigne le site internet www.rocmultisport.fr ou tout autre site internet exploité par la Société et mis à disposition dans le cadre des Services ;</p>
                    </li>
                    <li>
                        <p><span>« Utilisateur »</span> : désigne tout individu utilisant le Site et ayant accès à son contenu ;</p>
                    </li>
                </ul>
                
            </li>
        </ol>

        <h2>ARTICLE 2 – DONNEES COLLECTEES</h2>
        <ol>
            <li>
                <h3>Consentement</h3>
                <p>En naviguant sur notre Site, l’Utilisateur consent à la collecte et au traitement des données personnelles qu’il renseigne. Ce consentement sert de base légale au traitement des données collectées.</p>
                <p>Roc Multisport collecte et traite les données strictement nécessaires aux finalités pour lesquelles elles sont traitées. Nous nous engageons auprès de nos utilisateurs à ne pas traiter les données pour des finalités différentes que celles mentionnées ci-dessous. Si nous devions proposer un nouveau service sur notre Site, nécessitant la collecte et le traitement de données, nous nous engageons à collecter l’accord de nos utilisateurs une nouvelle fois avant de lui proposer le nouveau service dont il est question</p>
                <p>Chaque fois que notre Site traite des données personnelles, il prend toutes les mesures raisonnables pour s’assurer de l’exactitude et de la pertinence des données personnelles au regard des finalités pour lesquelles il les traite. </p>
            </li>
            <li>
                <h3>Accès aux données</h3>
                <p>Les données que nous collectons sur notre site sont à notre seul usage exclusif. Les données personnelles de nos utilisateurs ne sont pas communiquées à des tiers mais peuvent être accessibles par nos prestataires et sous-traitants informatiques dans le cadre de la maintenance et du développement du Site. Les données personnelles accessibles par nos prestataires et sous-traitants ne sont pas traitées, ni collectées ni exploitées par ces derniers qui peuvent uniquement y avoir accès pour la maintenance informatique.</p>
                <p>Le responsable du traitement de vos données de la Société est joignable à l’adresse suivante : remi@rocmultisport.fr ou benoit@rocmultisport.fr . En tant que responsable du traitement des données qu’il collecte, il s’engage à respecter le cadre des dispositions légales en vigueur. Il lui appartient notamment de fournir aux utilisateurs, une information complète sur le traitement de leurs données personnelles et de maintenir un registre des traitements conforme à la réalité. </p>
            </li>
        </ol>

        <h2>ARTICLE 3 – FINALITE DES TRAITEMENTS</h2>
        <p>Nous collectons les données des utilisateurs uniquement pour les finalités de traitement suivantes :</p>
        <ol>
            <li>
                <p><span>Réservation d’une activité</span> : Via notre formulaire de demande de réservation, tout Utilisateur peut réserver une activité mise à disposition par la Société. A ce titre, nous collectons les données personnelles suivantes : nom, prénom, n° de téléphone, courriel et adresse. Pour certaines activités nous collectons également la date de naissance du Client ainsi que celles des participants. Nous pouvons également être amenés à collecter les noms et prénoms des participants à des activités sélectionnées par le Client. Ces données nous servent à organiser nos prestations et à planifier l’activité choisie par le Client.</p>
            </li>
            <li>
                <p><span>Contacter la Société</span> : Une adresse électronique est accessible sur notre site ainsi qu’un formulaire de contact permettant aux Utilisateurs de contacter notre service clientèle. Nous collectons les courriels et nom de l’utilisateur afin de pouvoir traiter sa demande dans les meilleurs conditions.</p>
            </li>
            <li>
                <p><span>Paiement des commandes</span> : Sur notre Site, l’Utilisateur peut choisir de payer l’activité réservée via Carte Bancaire. Les données bancaires sont traitées via notre organisme de paiement – en fonction du choix du Client - qui assure l’intégralité de la confidentialité de ces données.</p>
            </li>
            <li>
                <p><span>Navigation sur notre site</span> : Notre Site collecte vos informations de navigation à des fins uniquement d’études statistiques. Nous vous invitons à vous référer à notre politique correspondante en matière de cookies.</p>
            </li>
            <li>
                <p><span>Prévenir et lutter contre la fraude informatique</span> (<em>spamming, hacking, etc.</em>) : matériel informatique utilisé pour la navigation, l’adresse IP, le mot de passe. </p>
            </li>
        </ol>
        <p>Nous ne dépassons pas les délais légaux de conservation des données et vos données sont conservées uniquement pour la durée nécessaire aux traitements des finalités pour lesquelles elles ont été collectées.</p>

        <h2>ARTICLE 4 – NON-COMMUNICATION DES DONNEES PERSONNELLES</h2>
        <p>Notre Société s’interdit de traiter, héberger ou transférer les Informations collectées sur ses utilisateurs vers un pays situé en dehors de l’Union européenne ou reconnu comme « non adéquat » par la Commission européenne sans en informer préalablement le propriétaire des données.</p>
        <p>Pour autant, notre Société reste libre du choix de ses sous-traitants techniques et commerciaux à la condition qu’ils présentent les garanties suffisantes au regard des exigences du Règlement Général sur la Protection des Données (RGPD : n° 2016-679). Les Données Personnelles de l’Utilisateur peuvent être traitées par des filiales de notre Société  et des sous-traitants (prestataires de services), exclusivement afin de réaliser les finalités de la présente politique.</p>
        <p>Quand Roc Multisport recourt aux services de prestataires ces derniers disposent d'un accès limité aux données de l'utilisateur, dans le cadre de l'exécution de ces prestations et ont une obligation contractuelle de les utiliser en conformité avec les dispositions de la réglementation applicable en matière protection des données à caractère personnel.</p>
        <p>La Société s’engage à prendre toutes les précautions nécessaires afin de préserver la sécurité des Informations et notamment qu’elles ne soient pas communiquées à des personnes non autorisées.</p>

        <h2>ARTICLE 5 – SECURITE DES DONNEES ET NOTIFICATION D’INCIDENT</h2>
        <p>Notre Site et notre Société ont pris toutes les précautions utiles et nécessaires, au regard de l’état de l’art en la matière, pour protéger vos informations dans un environnement sécurisé en vue d’éviter toute destruction, perte, altération, diffusion ou accès non autorisé. Quels que soient les efforts fournis, aucune méthode de transmission sur Internet et aucune méthode de stockage électronique n'est complètement sûre. Nous ne pouvons en conséquence pas garantir une sécurité absolue. Si nous prenions connaissance d'une brèche de la sécurité, nous avertirions les utilisateurs concernés afin qu'ils puissent prendre les mesures appropriées. Nos procédures de notification d’incident tiennent compte de nos obligations légales, qu'elles se situent au niveau national ou européen.</p>
        <p>Dans le cas où l’intégrité et la confidentialité de vos données sont compromises, le responsable du traitement s’engage à respecter les procédures mises en place au titre de la Loi Informatiques et Libertés du 6 janvier 1978 et du Règlement Européen sur la Protection des Données (« RGPD »).</p>

        <h2>ARTICLE 6 – DROITS DES PERSONNES</h2>
        <p>Au regard des dispositions légales de <em>la Loi Informatiques et Libertés du 6 janvier 1978 et du Règlement Européen sur la Protection des Données (« R.G.P.D »)</em>, les utilisateurs de notre Site disposent des droits suivants :</p>
        <ol>
            <li>
                <p><span>droit d'accès</span> <em>(article 15 RGPD)</em> et de <span>rectification</span> <em>(article 16 RGPD)</em>, de <span>mise à jour, de complétude</span> des données des Utilisateurs, droit de <span>verrouillage ou d’effacement</span> des données des Utilisateurs à caractère personnel (article 17 du RGPD), lorsqu’elles sont inexactes, incomplètes, équivoques, périmées, ou dont la collecte, l'utilisation, la communication ou la conservation est interdit.</p>
            </li>
            <li>
                <p>droit de <span>retirer</span> à tout moment un consentement (<em>article 13-2c RGPD</em>)</p>
            </li>
            <li>
                <p>droit à la <span>limitation</span> du traitement des données des Utilisateurs (<em>article 18 RGPD</em>)</p>
            </li>
            <li>
                <p>droit <span>d’opposition</span> au traitement des données des Utilisateurs (<em>article 21 RGPD</em>)</p>
            </li>
            <li>
                <p>droit à <span>la portabilité</span> des données que les Utilisateurs auront fournies, lorsque ces données font l’objet de traitements automatisés fondés sur leur consentement ou sur un contrat (<em>article 20 RGPD</em>)</p>
            </li>
            <li>
                <p>droit de <span>définir le sort des données</span> des Utilisateurs après leur mort et de choisir à qui Roc Multisport devra communiquer (<em>ou non</em>) ses données à un tiers qu’il aura préalablement désigné.</p>
            </li>
        </ol>
        <p>Notre site et notre Société ne peuvent pas s’opposer à la demande d’exercice de leurs droits par les utilisateurs. Toute autre demande peut s’effectuer à tout moment par voie électronique à l’adresse suivante : remi@rocmultisport.fr ou benoit@rocmultisport.fr . Les demandes seront traitées dans un délai de dix (10) jours ouvrés sauf motif impérieux avancé et justifié par notre Société justifiant un rallongement du délai.</p>

        <h2>ARTICLE 7 – SAISINE DE LA CNIL</h2>
        <p>Si notre Société ne satisfait pas la demande de l’utilisateur, ce dernier est en droit de saisir la CNIL (<em>Commission Nationale de l’Informatique et des Libertés, https://www.cnil.fr</em>) afin de faire prévaloir ses droits.</p>

        <h2>ARTICLE 8 – AGE MINIMUM</h2>
        <p>Conformément aux dispositions de l’article 8 du R.G.P.D., nous ne collectons pas, directement ou indirectement, de données à caractère personnel de personnes âgées de moins de seize (16) ans sans l’accord de leur tuteur légal. Les utilisateurs de moins de seize (16) ans sont invités à solliciter l’accord d’un représentant légal – requis par Roc Multisport - afin que ses données à caractère personnel puissent être collectées et pour pouvoir utiliser les services du Site.</p>
        <p>Roc Multisport se réserve le droit de demander un justificatif de cet accord du représentant légal. La responsabilité de notre Société ne pourra pas être recherchée en cas de fourniture par tout utilisateur de données personnelles concernant un mineur de moins de seize (16) ans.</p>

        <h2>ARTICLE 9 – DEFINITION DES COOKIES</h2>
        <p>L’utilisateur est informé qu’un cookie est un petit fichier déposé sur le terminal de tout utilisateur (ordinateur, tablette ou appareil mobile), par notre site, lors de sa consultation. Il ne contient aucune information personnelle, mais permet de faire le lien entre l’appareil de l’utilisateur et ses préférences d’utilisation et d’expérience sur notre site (<em>ex : le lieu, la langue, la taille des caractères</em>).</p>

        <h2>ARTICLE 10 – CONSENTEMENT EN MATIERE D’UTILISATION DES COOKIES</h2>
        <p>Pour l’utilisation de fichiers « <em>cookies</em> » impliquant la sauvegarde et l’analyse de données à caractère personnel, le consentement de l’utilisateur est toujours demandé. Ce consentement est valide pour une durée de treize (13) mois, au terme duquel une nouvelle autorisation sera demandée à l’utilisateur.</p>

        <h2>ARTICLE 11 – UTILISATION DES COOKIES</h2>
        <p>Nous utilisons et collectons les cookies aux fins de :</p>
        <ul>
            <li>De traiter des statistiques et informations sur le trafic sur notre site et d’optimiser au mieux ce dernier ; </li>
            <li>De proposer à nos utilisateurs une expérience de navigation fluide en adaptant la présentation de notre site aux préférences d’affichage du terminal de l’utilisateur ;</li>
            <li>De mémoriser des informations fournies sur la plateforme par l’utilisateur.</li>
        </ul>

        <h2>ARTICLE 12 – OPPOSITION ET CONFIGURATION</h2>
        <p>Tous les utilisateurs du Site peuvent s’opposer à l’enregistrement des « <em>cookies</em> » en configurant leur logiciel de navigation de la ou les manière(s) suivante(s) :</p>
        <ul>
            <li>Ouvrir une fenêtre de navigation privée ;</li>
            <li>Configuration des cookies via le Widget « <em>Cookies</em> » disponible en page d’accueil de notre site ;</li>
            <li>Configuration de l’ordinateur pour qu’un message apparaisse vous demandant d’accepter, de personnaliser ou de refuser les cookies sur chaque site ou de manière systématique ;</li>
            <li>Ou tout autre moyen à disposition de l’utilisateur.</li>
        </ul>
        <p>À tout moment l’utilisateur peut faire le choix d’exprimer et de modifier ses souhaits en matière de cookies. Roc Multisport décline toute responsabilité pour les conséquences liées au fonctionnement du site et des services éventuellement proposés résultant :</p>
        <ul>
            <li>Du refus de cookies par l’utilisateur ;</li>
            <li>Et/ou de l’impossibilité pour le site d’enregistrer ou de consulter les cookies nécessaires à leur fonctionnement du fait du choix de l’utilisateur.</li>
        </ul>

        <h2>ARTICLE 13 – PARAMETRAGE DU LOGICIEL DE NAVIGATION</h2>
        <p>L’utilisateur peut configurer son logiciel de navigation de manière à paramétrer ses choix en matière d’utilisation des cookies :</p>
        <ul>
            <li>Pour Microsoft Edge&trade;: https://support.microsoft.com/en-us/microsoft-edge</li>
            <li>Pour Safari&trade; : http://docs.info.apple.com/article.html?path=Safari/3.0/fr/9277.html</li>
            <li>Pour Chrome&trade;: http://support.google.com/chrome/bin/answer.py?hl=fr&hlrm=en&answer=95647</li>
            <li>Pour Firefox&trade;: http://support.mozilla.org/fr/kb/Activer%20et%20d%C3%A9sactiver%20les%20cookies</li>
            <li>Pour Opera&trade;: http://help.opera.com/Windows/10.20/fr/cookies.html</li>
        </ul>
        <p>L’utilisateur peut également paramétrer son navigateur pour accepter ou refuser au cas par cas les cookies avant leur installation, ou supprimer les cookies de son terminal. L’utilisateur est informé qu’en paramétrant son navigateur pour refuser les cookies, certaines fonctionnalités de notre site pourraient ne pas être accessibles et la responsabilité de notre Société ou de l’hébergeur ne pourrait être recherchée à ce titre.</p>

        <h2>ARTICLE 14 – PARAMETRAGE DES RESEAUX SOCIAUX</h2>
        <p>En cliquant sur les icônes dédiées aux réseaux sociaux figurant sur notre site, Facebook et Instagram, et si l’utilisateur a accepté le dépôt de cookies en poursuivant sa navigation sur le site, ces réseaux sociaux peuvent également déposer des cookies sur les terminaux de l’utilisateur.</p>
        <p>L’utilisateur peut consulter la politique de protection des données de ces réseaux sociaux pour paramétrer les cookies correspondants.</p>
        <ul>
            <li>Facebook : https://www.facebook.com/policy.php</li>
            <li>Instagram : https://help.instagram.com/519522125107875</li>
        </ul>

        <h2>ARTICLE 15 – MODIFICATION DE LA POLITIQUE DE CONFIDENTIALITE</h2>
        <p>Roc Multisport se réserve le droit de modifier la présente Politique à tout moment. Si une modification est apportée à la présente Politique, la nouvelle version sera publiée immédiatement sur le Site. Si l’Utilisateur n’est pas d’accord avec les termes de la nouvelle rédaction de la politique, il a la possibilité de ne plus utiliser les Services du Site et de ne plus naviguer sur le Site.</p>
    </main>
    <footer>
        <?php require("partials/footer.php") ?>
    </footer>
</body>