<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC - Register</title>
</head>
<body>
    
    <form method="post" action="register.php">
        <label for="lastName">Nom</label>
        <input type="text" id="lastName" name="lastName">
        <label for="firstName">Prénom</label>
        <input type="text" id="firstName" name="firstName">
        <label for="mail">Email</label>
        <input type="text" id="mail" name="mail">
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password">
        <button type="submit">S'enregistrer</button>

    </form>

</body>
</html>