<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - Reservation Page</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="" type="css/normalize/css" />
    <link rel="stylesheet" href="css/style.css">
</head>
<body class="form">
    <header>
        <?php require('partials/header.php') ?> 
    </header>
    <main class="temporaryBooking">
        <div class="alert">
            <p>Encore un peu de patience... la réservation en ligne arrive prochainement !</p>
            <p>Pour le moment, vous pouvez nous contacter par <a href="contact.php">mail</a> ou par téléphone au <a href="tel:0658355166">O6.58.35.51.66.</a></p>
        </div>
    </main>
    <footer>
        <?php require('partials/footer.php') ?>
    </footer>
    <script type="module" src="js/app.js"></script>
</body>
</html>
