<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROC Multisport - Politique de confidentialité</title>
    <link rel="icon" href="img/background/logoRocMultisport.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="" type="css/normalize/css" />
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <?php require('partials/header.php') ?> 
    </header>   

    <main class="policy">
        <h1>CONDITIONS GENERALES DE VENTE</h1>
        <p><span>Préambule</span></p>
        <p>Les présentes Conditions Générales de Vente (<em>ci-après entendues comme « C.G.V. »</em>) s’appliquent sur la vente des services du Site www.rocmultisport.fr (<em>ci-après entendu comme le « Site »</em>) et définissent les droits et obligations du Prestataire et du Client dans le cadre de la fourniture en ligne des Services du Prestataire.</p>
        <p>Les C.G.V. s’appliquent sans restriction ni réserves à tous les utilisateurs et clients du Site voulant
        procéder à la réservation des services du Prestataire.</p>
        <p>Le Client reconnaît et accepte que la poursuite de la navigation sur le Site vaut acceptation sans réserve
        des dispositions et conditions de vente qui suivent. Il reconnaît avoir accepté les Conditions avant de
        souscrire à une activité sur le Site, le fait de souscrire à un service emportant l’adhésion entière,
        immédiate et sans réserve par le Client des Conditions en vigueur au moment de la souscription.</p>
        <p>La version actuelle de ces Conditions est la seule opposable aux Clients et aux Utilisateurs du Site :</p>
        <ul>
            <li>Pendant toute la durée d’utilisation du Site et jusqu’à ce qu’une nouvelle version la remplace. Roc
                Multisport se réserve le droit de modifier à tout moment les présentes Conditions sans en avertir au
                préalable le Client mais tiendra informé ce dernier des modifications ;</li>
            <li>Pour toute souscription des services du Site ;</li>
        </ul>
        <p>Les Conditions prévalent sur tout autre document émanant de Roc Multisport ou de toutes autres
        conditions générales d’achat. Roc Multisport se réserve le droit de déroger à certaines clauses des
        présentes ou d’établir des conditions générales de vente particulières en fonction des clients.</p>
        <p>Les présentes Conditions sont entrées en vigueur <span>25 avril 2021</span>.</p>

        <p><span>Définitions</span></p>
        <p>Dans les présentes Conditions les termes suivants sont entendus comme suit :</p>
        <ul>
            <li>
                <span>« Activité sportive »</span> : désigne l’une ou l’autre des activités proposées par le Prestataire via le
                Site ;
            </li>
            <li>
                <span>« Client »</span> : désigne toute personne physique âgée de 18 ans au moins (selon les dispositions de l’article liminaire du Code de la Consommation, toute personne physique qui agit à des fins qui n’entrent pas dans le cadre de son activité commerciale, industrielle, artisanale, libérale ou agricole) et tout professionnel personne physique qui réalise une démarche de réservation d’une activité sportive sur le Site ;
            </li>
            <li>
                <span>« Conditions »</span> : désigne les présentes conditions générales de vente ;
            </li>
            <li>
                <span>« Moniteur »</span> : désigne tout encadrant professionnel de la Société Roc Multisport des activités proposées sur le Site et diplômé d’Etat ;
            </li>
            <li>
                <span>« Participant(s) »</span> : personne(s) physique(s) renseignées dans le formulaire de réservation comme prenant part à l’activité sportive sélectionnée par le Client et constituant le groupe dans son ensemble ;
            </li>
            <li>
                <span>« Services »</span> : désigne les activités sportives proposées par le Prestataire au Client sur le Site ;
            </li>
            <li>
                <span>« Site »</span> : désigne le site internet www.rocmultisport.fr ou tout autre site internet exploité par le Prestataire et mis à disposition dans le cadre des Services ; 
            </li>
            <li>
                <span>« Tarif »</span> : désigne le prix applicable aux Services sur le Site ;
            </li>
            <li>
                <span>« Utilisateur »</span> : désigne tout utilisateur du Site ;
            </li>
        </ul>
        <p>Aux termes des présentes, le Prestataire ou le Client pourront être désignés individuellement comme la <span>« Partie »</span> et collectivement comme les <span>« Parties »</span>.</p>

        <h2>Article 1 – Le Prestataire</h2>
        <p>Le Prestataire proposant les activités sportives via le Site est la <span>Société Roc Multisport</span>, Société à Actions Simplifiées, au capital social de 5.000 €, immatriculée au R.C.S. de Annecy sous le n°879 169 514 et dont le siège social est sis 165 Route des Tappes 74230 Dingy-Saint-Clair.</p>

        <h2>Article 2 – Description des Services</h2>
        <p>Via le Site, le Prestataire met à disposition des Utilisateurs un ensemble d’activités sportives soumises à réservation.</p>
        <ol>
            <li>
                <h3>VTT à Assistance Electrique (dit « VTTAE »)</h3>
                <p>Tout Utilisateur a la possibilité de réserver un ou plusieurs VTTAE afin de partir à la découverte d’un ou plusieurs sentiers délimités. Cette activité se fait obligatoirement sous le contrôle d’un moniteur.</p>
                <p>La réservation de cette activité est soumise aux conditions suivantes :</p>
                <ul>
                    <li>L’activité est réservée aux enfants et adultes plus de 8 ans ;</li>
                    <li>L’activité est réservée aux groupes de minimum 4 participants et maximum 8 participants ;</li>
                    <li>Le matériel est fourni par le Prestataire (VTTAE, casque, gants) à l’exception des vêtements et chaussures adaptés à la pratique d’un VTTAE.</li>
                </ul>
            </li>
            <li>
                <h3>Paddle,Kayak</h3>
                <p>Roc Multisport propose à ses Clients des sorties nautiques en paddle ou Kayak autour du lac d’Annecy. Cette activité se fait obligatoirement sous le contrôle d’un moniteur.</p>
                <p>La réservation de cette activité est soumise aux conditions suivantes :</p>
                <ul>
                    <li>L’activité est réservée aux enfants et adultes de plus de 6 ans ;</li>
                    <li>Le matériel est fourni par le Prestataire (paddle, Kayak, pagaie, gilet) à l’exception des vêtements adaptés à la pratique du paddle et du kayak ;</li>
                    <li>L’activité est réservée aux groupes de minimum 4 participants et maximum 8 participants.</li>
                </ul>
            </li>
            <li>
                <h3>Escalade, Via Ferrata </h3>
                <p>L’escalade est une activité sportive se pratiquant sur des parois en extérieur (en SNE, structure naturelle d’escalade). La Via ferrata est une activité de plein air, permettant aux participants de progresser en escalade via un itinéraire aménagé dans une paroi rocheuse, équipée avec des éléments métalliques. Ces activités se font obligatoirement sous le contrôle d’un moniteur.</p>
                <p>La réservation de cette activité est soumise aux conditions suivantes : </p>
                <ul>
                    <li>L’activité est réservée aux enfants et adultes de plus de 8 ans ;</li>
                    <li>Le matériel est fourni par le Prestataire (baudriers, casques, descendeurs, cordes, mousquetons, longes) à l’exception des chaussures d’escalade et des vêtements adaptés à la pratique de ces activités ;</li>
                    <li>L’activité est réservée aux groupes de minimum 4 participants et maximum 8 participants.</li>
                </ul>
            </li>
            <li>
                <h3>Tir à l’arc</h3>
                <p>Roc Multisport propose à ses Clients de s’initier à la pratique du Tir à l’Arc. Cette activité se fait obligatoirement sous le contrôle d’un moniteur.</p>
                <p>La réservation de cette activité est soumise aux conditions suivantes : </p>
                <ul>
                    <li>L’activité est réservée aux enfants et adultes de plus de 7 ans ;</li>
                    <li>Le matériel est fourni par le Prestataire (arc, cibles, flèches, blasons) à l’exception des vêtements adaptés ;</li>
                    <li>L’activité est réservée aux groupes de 6 personnes minimum (sauf si le Client a sélectionné l’option « Cocktail d’activités ») et maximum 12 participants.</li>
                </ul>
            </li>
            <li>
                <h3>Snowboard / Splitboard</h3>
                <p>Accompagné d’un moniteur, Roc Multisport propose à ses Clients de s’initier au Snowboard au départ de La Clusaz.</p>
                <p>La réservation de cette activité est soumise aux conditions suivantes : </p>
                <ul>
                    <li>L’activité est réservée aux enfants et adultes de plus de 7 ans ;</li>
                    <li>Le matériel n’est pas fourni par le Prestataire. En procédant à la réservation de cette activité, le Client s’engage à ce que lui et les autres participants disposent du matériel recommandé et adéquat. Pour le hors-piste et la randonnée, le Client et les autres participants doivent obligatoirement fournir le matériel de sécurité requis (dva, pelle, sonde) ;</li>
                    <li>Le Stage RockEasy (pour les débutants) est disponible à partir de 3 participants et ne peut dépasser 8 participants ;</li>
                    <li>L’activité de Snowboard est possible à partir de 2 participants et pour un maximum de 8 participants ;</li>
                    <li>L’activité de randonnée Splitboard est possible à partir de 2 participants et pour un maximum de 6 participants.</li>
                </ul>
            </li>
            <li>
                <h3>Cocktail d’activités Roc</h3>
                <p>Les Clients peuvent également souscrire à la formule <span>« Cocktail d’activités »</span> permettant la réservation de plusieurs activités sportives.</p>
                <p>La réservation de cette activité est soumise aux conditions suivantes : </p>
                <ul>
                    <li>La formule est accessible dès 7 ans ;</li>
                    <li>Les activités se font obligatoirement sous le contrôle d’un moniteur ;</li>
                    <li>Le matériel est fourni à l’exception du matériel de Snowboard, de Splitboard et du matériel de sécurité et des vêtements et chaussures adaptées ;</li>
                    <li>La formule est accessible aux groupes de minimum 4 participants et maximum 8 participants.</li>
                </ul>
            </li>
            <li>
                <h3>Conditions communes aux activités</h3>
                <p>Pour chaque activité, le Client est informé qu’il est possible de compléter un groupe déjà constitué s’il n’atteint pas le nombre minimal de participants. La décision de joindre plusieurs groupes sera prise par le Prestataire seul, sans approbation préalable du Client. Aucun remboursement ne sera dû au Client si ce dernier refuse la jonction des groupes et/ou d’annuler l’activité sur ce motif.</p>
                <p>Le jour de l’activité, si le nombre de participants est inférieur au nombre souscrit par le Client et si ce dernier n’en a pas informé le Prestataire au plus tard 48h avant la réservation, le Client est informé que toute place réservée est due et ne pourra donner lieu à un remboursement.</p>
                <p>L’ensemble des activités se déroule sur des forfaits d’une journée (6 à 7h en fonction de l’activité choisie et des conditions météorologiques) ou d’une demi-journée (3 heures)</p>
                <p>Pour toute demande concernant l’organisation d’un évènement particulier (EVG/EVJF, séminaires, anniversaires, groupes de plus de 8 participants), l’Utilisateur est invité à contacter la Société pour une demande de devis. La signature du devis vaut acceptation par le Client des présentes Conditions Générales de Vente.</p>
                <p>Pour toute activité, le Client devra se présenter au lieu indiqué entre 15min et 30min avant l’heure de début de l’activité afin que le Prestataire puisse procéder à un briefing du Client, préparer le matériel avec lui et faire un rappel des mesures de sécurité.</p>
            </li>
        </ol>

        <h2>Article 3 – Responsabilités et Obligations du Client</h2>
        <ol>
            <li>
                <h3>Condition physique des participants </h3>
                <p>Pour chaque activité réservée par le Client, ce dernier garanti que lui et l’ensemble des participants ont la condition physique requise pour la pratique de ce type d’activité sportive. A ce titre, le Client garanti que tous les participants disposent d’une <span>assurance responsabilité civile</span> permettant de les protéger en cas d’accident et n’aient pas de contre-indication physique à la pratique de l’activité réservée.</p>
                <p>Le Client est informé que la pratique d’une ou plusieurs activités peut être interdite par le Prestataire aux femmes enceintes. Si le Client ne l’a pas spécifié au Prestataire le jour de la réservation, il ne pourra solliciter de remboursement.</p>
                <p>Pour les activités nautiques, le Client s’engage pour sa personne ainsi que pour l’ensemble des participants de l’activité à ce que chaque participant sache nager et s’immerger. Le Client – <em>avec le moniteur</em> – devra s’assurer que chaque personne porte un gilet d’aide à la flottabilité durant toute la durée de l’activité.</p>
                <p>Pour chaque activité, le Client reconnaît avoir pris connaissance des conditions météorologiques et de toute consigne de sécurité et réglementation liées à l’activité souscrite.</p>
            </li>
            <li>
                <h3>Responsabilité du Client </h3>
                <p>Le Client est responsable des dommages corporels ou matériels occasionnés aux tiers et/ou aux biens du Prestataire, de son fait. La responsabilité de la Société ne pourra être recherchée en cas de dommages subis par le Client du fait des tiers, des autres participants ou de sa propre utilisation du matériel mis à sa disposition ou du non-respect par le Client ou un participant des consignes délivrées par le moniteur durant l’activité.</p>
                <p>A cet effet, le Client s’engage à disposer d’une assurance responsabilité civile et être couverts pour tous risques matériels et corporels.</p>
            </li>
            <li>
                <h3>Comportement du Client</h3>
                <p>Durant toute la durée de l’activité, le Client s’engage à :</p>
                <ul>
                    <li><span>Suivre et respecter les consignes données par le moniteur, en particulier les consignes de sécurité</span>. Le moniteur se réserve le droit, en cas de non-respect de ces règles par l’un ou l’autre des participants ou en cas d’attitude dangereuse ou mettant en danger les autres participants ou le moniteur, à interrompre l’activité. Le Client ne pourra solliciter aucune demande de remboursement ou l’octroi d’indemnités à ce titre.</li>
                    <li><span>Ne pas abandonner le matériel fourni par le Prestataire.</span> Le Client devra prendre grand soin du matériel fourni et devra le restituer dans leur état originel. Le Prestataire pourra facturer au Client tous frais de réparation et de remplacement du matériel endommagé ou perdu. </li>
                    <li><span>Ne pas pratiquer l’activité en état d’ébriété</span>, ne pas transporter ni consommer d’alcool ou de stupéfiants durant l’activité et respecter l’interdiction de fumer ; </li>
                    <li><span>Respecter la faune et la flore environnante ;</span></li>
                    <li><span>Informer le moniteur de toute contre-indication médicale</span> à l’activité choisie et de toute blessure ou lésion pouvant avoir un impact sur la pratique de l’activité ;</li>
                </ul>
            </li>
            <li>
                <h3>Informations fournies par le Client</h3>
                <p>Le Client s’engage à fournir des informations correctes et complètes. Sa responsabilité pourra être engagée en cas d’informations erronées, manquantes ou tronquées, ayant eu un impact direct ou indirect sur la réalisation de la prestation, en particulier sur la sélection des niveaux de compétences de chaque participant pour les activités sportives sélectionnées.</p>
            </li>
            <li>
                <h3>Matériel requis</h3>
                <p>Le Client s’engage à fournir le matériel requis pour chaque activité – à l’exception du matériel fourni par la Société et indiqué sur chaque fiche d’activité. Le Client est informé qu’en cas de non-fourniture du matériel requis ou en cas de matériel non approprié, l’activité réservée pourra être annulée ou reportée par le Prestataire, sans que le Client ne puisse solliciter de remboursement, l’octroi d’indemnités ou rechercher la responsabilité du Prestataire.</p>
            </li>
            <li>
                <h3>Présence des enfants</h3>
                <p>Chaque activité est soumise à une limite d’âge minimum que le Client s’engage à respecter. Le Prestataire pourra, en cas de doute, solliciter du Client la copie d’une pièce d’identité ou tout document pouvant attester de l’âge d’un participant.</p>
                <p>Le Client devra fournir une <span>autorisation parentale</span> pour tous les mineurs de moins de 12 ans inscrits à une activité sans la présence de leurs représentants légaux.</p>
                <p>Le Client est également informé que le Prestataire ne peut prendre plus de 12 enfants de moins de 18 ans par groupe par activité. Au-delà de cette capacité maximale, le Prestataire devra solliciter l’accompagnement d’un moniteur supplémentaire, dont les frais seront à la charge du Client.</p>
                <p>Le Client accepte que le non-respect de l’une ou l’autre des dispositions au présentes pourra entraîner l’annulation immédiate de sa réservation sans pouvoir donner lieu à un quelconque remboursement.</p>
            </li>
        </ol>

        <h2>Article 4 – Réserver une activité</h2>
        <p>Tout Utilisateur souhaitant réserver une activité sportive de Roc Multisport doit suivre les étapes suivantes :</p>
        <ol>
            <li>
                <h3>Sélection des activités via le formulaire de demande de réservation</h3>
                <p>L’Utilisateur doit faire le choix des activités dont il souhaite procéder à la réservation. Pour chacune d’entre elles il doit renseigner la date et le nombre de participants. Pour chaque participant, le Client doit renseigner le nom, prénom et date de naissance. Pour certaines activités, des informations complémentaires pourront être demandées telles que la taille ou le niveau de compétence du participant dans l’activité sélectionnée. </p>
                <p>Un récapitulatif de sa réservation lui sera alors envoyé par mail.</p>
            </li>
            <li>
                <h3>Paiement du prix</h3>
                <p>Le Client doit ensuite renseigner ses coordonnées et procéder au paiement total de la réservation via Carte bleue. Le Client sera alors redirigé vers un écran de confirmation l’invitant à confirmer sa commande. La validation de la commande par le Client vaut conclusion d’un contrat de prestation de services entre le Prestataires et le Client et acceptation par ce dernier sans réserve des présentes CGV.</p>
                <p>Le Client recevra une confirmation de sa réservation sous un délai de 48h après la souscription aux services.</p>
                <p>Si la date d’activité choisie par le Client n’est plus disponible, Roc Multisport prendra contact dans les plus brefs délais avec le Client afin de convenir d’une autre date.</p>
            </li>
        </ol>

        <h2>Article 5 – Contrôle des réservations</h2>
        <ol>
            <li>
                <h3>Modification et annulation des réservations par le Client</h3>
                <p>Tout Client a la possibilité de modifier ou annuler sa réservation jusqu’à 48h avant la date prévue de l’évènement. Passé ce délai, aucun remboursement ne sera effectué par la Société.</p>
                <p>Passé le délai de 48h, le Prestataire n’accepte les modifications et annulations de réservations qu’en cas de force majeure ou de maladie du Client, sous réserve de fourniture d’un justificatif médical.</p>
            </li>
            <li>
                <h3>Refus d’une réservation</h3>
                <p>Le prestataire se réserve le droit de suspendre toute réservation en cas de refus d’autorisation de paiement de la part des organismes de paiement officiellement accrédités ou en cas de non-paiement de la réservation.</p>
                <p>Le Prestataire se réserve également le droit de refuser toute réservation émanant d’un Client qui n’aurait pas réglé totalement ou partiellement une réservation précédente ou avec lequel un litige de paiement serait en cours de traitement. Cette disposition est applicable en cas de réservation précédente faite en ligne, ou par devis, par téléphone, par le biais d’un bon de commande ou tout autre canal de vente du Prestataire.</p>
                <p>Le Prestataire se réserve également le droit de refuser toute réservation émanant d’un Client qui aurait déjà eu recours aux services du Prestataire mais qui n’aurait pas respecté les consignes du Prestataire, ni les consignes de sécurité ou l’une ou l’autre des dispositions des présentes Conditions générales de vente.</p>
            </li>
        </ol>

        <h2>Article 6 – Prix et modalités de paiement</h2>
        <ol>
            <li>
                <h3>Tarifs</h3>
                <p>Les prix affichés sur le Site sont indiqués en euros € TTC et sont ceux en vigueur au moment de la confirmation de la réservation par le Client.</p>
                <p>Le Prestataire se réserve le droit de modifier ses prix à tout moment mais s’engage à appliquer les tarifs en vigueur au moment de la réservation par le Client.</p>
                <p>Le paiement de la totalité du prix doit être réalisé lors de la réservation. Les sommes versées ne pourront être considérées comme des arrhes ou des acomptes. Aucune modalité d’escompte n’est prévue aux termes des présentes C.G.V.</p>
            </li>
            <li>
                <h3>Modalités de paiement</h3>
                <p>Toute réservation implique un règlement de la part du Client. Le prix est payable en totalité et en un seul versement, immédiatement au moment de la réservation, par carte bleue.</p>
            </li>
            <li>
                <h3>Factures</h3>
                <p>Après avoir réservé une activité, le Client recevra une facture et un récapitulatif par courrier électronique, 48h après la réservation.</p>
            </li>
            <li>
                <h3>Incidents de paiement</h3>
                <p>Le client consommateur est informé que tout retard de paiement de toute ou partie d’une somme due à son échéance entraînera automatiquement la déchéance du terme de l’ensemble des sommes dues.</p>
                <p>En outre, en cas de non-respect des conditions de paiement figurant ci-dessus, le Prestataire se réserve  le droit de suspendre l’accès au Site et de suspendre toute réservation, jusqu’à régularisation des factures.</p>
                <p>Ces dispositions s’appliquent sans préjudice de toutes autres actions judiciaires ou extrajudiciaires que le Prestataire serait en droit d’intenter à l’encontre du client pour obtenir le paiement de ses factures.</p>
            </li>
            <li>
                <h3>Incidents de paiement applicables aux professionnels</h3>
                <p>Les clients professionnels sont informés que tout retard de paiement des factures, à compter du jour suivant la date d’échéance de celles-ci, entraînera de plein droit l’application de pénalités de retard calculées sur le montant hors taxes impayé, et égales à au moins trois fois le taux d’intérêt légal en vigueur. Elles sont exigibles de plein droit et sans mise en demeure préalable.</p>
                <p>En outre, en application de <em>l’article L. 441-10 du Code de commerce</em>, une indemnité forfaitaire pour frais de recouvrement de 40,00 € sera due par le Client au Prestataire, et ce même en cas de règlement partiel de la facture, sans préjudice de toute autre action que le Prestataire serait en droit d’intenter à l’encontre du Client et aux frais de ce dernier aux fins de recouvrement de ses factures et de tous autres dommages et intérêts qui pourraient lui être dus.</p>
            </li>
        </ol>

        <h2>Article 7 – Droit de rétractation</h2>
        <p>Conformément aux dispositions de <em>l’article L.221-18 du Code de la Consommation</em> « le consommateur dispose d’un délai de quatorze jours pour exercer son droit de rétractation d’un contrat conclu à distance, sans avoir à motiver sa décision ni à supporter d’autres coûts que ceux prévus aux articles L.221-23 à L.221-25 ».</p>
        <p>Toutefois, en vertu de <em>l’article L.221-28 du même code</em>, le droit de rétractation ne s’applique pas aux contrats « <em>de fourniture de services pleinement exécutés avant la fin du délai de rétractation et dont l’exécution a commencé après accord préalable exprès du consommateur et renoncement exprès à son droit de rétractation » ainsi qu’aux contrats de « prestations de services d'hébergement, autres que d'hébergement résidentiel, de services de transport de biens, de locations de voitures, de restauration ou d'activités de loisirs qui doivent être fournis à une date ou à une période déterminée</em>. ».</p>

        <h2>Article 8 – Données personnelles</h2>
        <p>Les obligations du Prestataire relatives à la protection des données personnelles du Client sont décrites dans l’onglet « <em>Protection des Données Personnelles</em> » sur le Site.</p>

        <h2>Article 9 – Propriété intellectuelle</h2>
        <ol>
            <li>
                <h3>Le site </h3>
                <p>Toutes les marques, photographies, textes, commentaires, illustrations, images animées ou non, séquences vidéo, sons, ainsi que toutes les applications informatiques qui pourraient être utilisées pour faire fonctionner le Site et plus généralement tous les éléments reproduits ou utilisés sur le Site sont protégés par les lois en vigueur au titre de la propriété intellectuelle.</p>
                <p>Ils sont la propriété pleine et entière du Prestataire et de ses partenaires. Toute reproduction, représentation, utilisation ou adaptation, sous quelques formes que ce soit, de tout ou partie de ces éléments, y compris les applications informatiques, sans l'accord préalable et écrit du Prestataire, sont strictement interdites. Le fait pour le Prestataire de ne pas engager de procédure dès la prise de connaissance de ces utilisations non autorisées ne vaut pas acceptation desdites utilisations et renonciation aux poursuites.</p>
                <p>Il est strictement interdit au Client de :</p>
                <ul>
                    <li><em>Copier, reproduire, représenter, diffuser, distribuer, publier, de façon permanente ou provisoire, tout ou partie du contenu et/ou du site par tout moyen et sur tout support connu ou inconnu à ce jour ;</em></li>
                    <li><em>Créer des œuvres dérivées à partir du contenu et/ou du Site ;</em></li>
                    <li><em>Modifier, traduire, adapter, arranger, tout ou partie du Contenu du Site ;</em></li>
                    <li><em>Désassembler, décompiler, effectuer de l’ingénierie inverse sur le Site.</em></li>
                </ul>
                <p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des <em>articles L.335-2 et suivants du Code de la Propriété Intellectuelle</em>.</p>
            </li>
            <li>
                <h3>La Marque Roc Multisport</h3>
                <p>Les marques verbales et visuelles (logos) du Prestataire sont protégées. Leur utilisation sans autorisation écrite du Prestataire, sur tout support, à des fins de valorisation de produits ou de services, ou à des fins commerciales, est interdite sous peine de poursuites pénales et civiles engagées par le Prestataire à l’encontre du Client.</p>
            </li>
        </ol>

        <h2>Article 10 – Responsabilités et obligations</h2>
        <ol>
            <li>
                <h3>Obligations générales</h3>
                <p>Le Prestataire s’engage à fournir les services indiqués aux présentes conformément aux règles de l’art et de la meilleure manière. Il est à ce titre tenu d’une obligation de moyens et non de résultat. Il lui appartient de mettre en place les ressources humaines et de s’équiper des ressources matérielles nécessaires à l’exécution de sa mission.</p>
                <p>Le Prestataire s’engage à fournir au Client un matériel conforme et en bon état et à donner toutes les explications nécessaires sur la difficulté technique et physiques des activités réservées par le Client.</p>
                <p>Le Prestataire s’engage à être assuré par une assurance responsabilité civile.</p>
                <p>Le Prestataire n’est pas responsable des objets emportés par les participants pendant toute la durée de l’activité.</p>
                <p>Le Prestataire s’engage à informer le Client sur les caractéristiques essentielles des services fournis, avant la signature des présentes. Le Client est informé que l’activité sélectionnée n’est définitivement réservée qu’à compter de la réception, sous 48 heures, du mail de confirmation par la Société.</p>
                <p>Si la date choisie par le Client n’est pas disponible, une date de report sera proposée au Client. Ce dernier est donc informé que le Calendrier fourni sur le Site n’est donné qu’à titre indicatif et qu’avant la réception du mail de confirmation, la responsabilité du Prestataire ne pourra être recherchée si la date souhaitée par le Client n’est pas disponible.</p>
                <p>Le Prestataire est seul responsable du fait de ses préposés. Le Prestataire et le Client conviennent que ni l’un ni l’autre n’encourent de responsabilité à raison de toute perte de bénéfices, de clientèles ou de trouble commercial que l’un ou l’autre subirait.</p>
                <p>La responsabilité du Prestataire ne pourra être recherchée en cas d’utilisation par le Client des services d’une façon non prévue aux présentes et/ou contraire aux recommandations du Prestataire.</p>
            </li>
            <li>
                <h3>Annulation à l’initiative du Prestataire</h3>
                <p>Le Prestataire peut décider d’annuler une activité en cas de force majeure, notamment du à de mauvaises conditions météorologiques, à l’état de forme physique ou à l’aptitude des participants à la pratique de l’activité.</p>
                <p>Le Prestataire remboursera le Client si l’annulation est dû à des conditions météorologique défavorables.</p>
                <p>Pour chaque activité, le Client doit fournir au Prestataire des informations relatives à la condition physique de chaque participant. Si le Client ne fourni par ces informations ou fourni des informations erronées, incomplètes ou si le Client a délibérément menti sur l’état physique d’un participant, cette condition physique ayant un impact direct ou indirect sur la réalisation de la prestation et la pratique de l’activité choisie, le Prestataire pourra annuler l’activité pour le participant et aucun remboursement ne sera dû au Client. Cette disposition est prise pour la sécurité de l’ensemble des participants.</p>
            </li>
        </ol>

        <h2>Article 11 – Force majeure</h2>
        <p>En cas de survenance d’un événement de force majeure, tel que défini par la loi et la jurisprudence des juridictions françaises, rendant impossible pour l’une des Parties, l’exécution de ses obligations pendant plus de trente (30) jours, et si le cas de force majeure perdure, chacune des parties aura le droit de résoudre le présent contrat de plein droit, sans qu’aucune indemnité ne soit due par l’une ou l’autre des parties, par Lettre recommandée avec avis de réception adressée à l’autre partie.</p>
        <p>Les Parties ne pourront en aucun cas être tenues responsables de toutes inexécutions et/ou ruptures de Contrat nées d’un cas de force majeure et aucune indemnité ne pourra être réclamée par une Partie à l’autre à ce titre.</p>
        <p>Cependant, dès la disparition de la cause de la suspension de leurs obligations réciproques, les parties feront tous leurs efforts pour reprendre le plus rapidement possible l'exécution normale de leurs obligations contractuelles. A cet effet, la partie empêchée avertira l'autre de la reprise de son obligation par lettre recommandée avec demande d'avis de réception ou tout acte extrajudiciaire.</p>

        <h2>Article 12 – Loi applicable et règlement des litiges</h2>
        <ol>
            <li>
                <h3>Dispositions générales</h3>
                <p>Les présentes Conditions générales et les opérations qui en découlent sont régies par le droit français.</p>
                <p>Les Parties s’engagent à rechercher une solution amiable à tout différend qui pourrait naître de l’interprétation ou de l’exécution des présentes. A ce titre, la partie qui souhaite mettre en jeu la procédure amiable de conciliation devra notifier à l’autre partie, par lettre recommandée avec demande d’accusé de réception, son intention de mettre en jeu ladite procédure en précisant les difficultés d’application rencontrées ou les manquements constatés.</p>
                <p>La présente procédure de règlement amiable constitue un préalable obligatoire à l'introduction d'une action en justice entre les Parties. Toute action introduite en justice en violation de la présente clause serait déclarée irrecevable.</p>
                <p>Si les parties ne parviennent pas à trouver un accord amiable sous un délai de trente (30) jours calendaires suivant la première notification, chacune d’entre elles recouvrera sa pleine liberté d’action.</p>
                <p>A défaut de parvenir à une résolution amiable malgré les diligences entreprises, tout litige relatif à l'exécution, à l’interprétation, à la validité et à la résolution des Conditions sera soumis aux tribunaux compétents dans les conditions de droit commun.</p>
            </li>
            <li>
                <h3>Médiation</h3>
                <p>La Commission Européenne a mis en place une plateforme de règlement en ligne des litiges, permettant le règlement indépendant par voie extrajudiciaire des litiges en lignes entre consommateurs et professionnels de l’Union Européenne. Cette commission est accessible à l’adresse suivante : https://webgate.ec.europa.eu/odr/ . Ladite procédure est gratuite. Le client peut, à ses frais, se faire assister par le conseil de son choix.</p>
                <p>Le Client est libre d’accepter ou de refuser le recours à la médiation et/ou toute solution éventuelle proposée par le médiateur.</p>
            </li>
        </ol>

        <h2>Article 13 – Clauses diverses</h2>
        <p>Divisibilité : Si une ou plusieurs stipulations des présentes Conditions sont tenues pour non valides ou déclarées nulles en application d’une loi ou d’un règlement ou à la suite d’une décision de justice ayant autorisé de la chose jugée, cela ne remet pas en cause les autres clauses des Conditions.</p>
        <p>Non-renonciation : Le fait que le Prestataire le Client ne se soient pas prévalu d’un manquement par l’autre partie à l’une des obligations visées dans les présentes Conditions ne sera pas interprété pour l’avenir comme une renonciation à l’obligation en cause.</p>
        <p>Nullité partielle : En cas de contradiction entre une stipulation des Conditions et tout texte législatif, loi, ordonnance, réglementation, ordonnance judiciaire ou convention collective, présent ou futur, ces derniers prévaudront, sous réserve que la stipulation des présentes ainsi affectée ne soit limitée que dans la mesure nécessaire et qu’aucune autre stipulation ne soit affectée.</p>
        <p>Langue des Conditions : Les présentes Conditions générales et les opérations qui en découlent sont régies par le droit français. Elles sont rédigées en langue française. Dans le cas où elles seraient traduites en une ou plusieurs langues, seul le texte français ferait foi en cas de litige.</p>
        <p>Absence d’affectio societatis : Les Parties conviennent que les Conditions excluent toute volonté de créer une société, une association ou toute autre structure ayant pour objet de mettre en commun des compétences ou de partager de quelconques bénéfices sous quelques formes que ce soit.</p>

    </main>
    <footer>
        <?php require("partials/footer.php") ?>
    </footer>
</body>